### ISSUE TITLE
option for standard error bands

### ISSUE THREAD

**Issue by laszlosandor** [michaelstepner/binscatter#19]
Or this is pointless in the current architecture, one would basically need to run a regression incl. bin dummies instead of residualizing etc.?

Amazing that it's still faster to regress, residualize and remean than having one regression but with nq new binary tempvars generated and thrown in.

**Comment by felixholub** [comment]
Is there any plan to implement this feature? Or have you found an alternative solution @laszlosandor ?

**Comment by laszlosandor** [comment]
Hi Felix, Sorry, I have not found other solutions either.

**Comment by michaelstepner** [comment]
@felixholub No plans to implement this feature. I currently consider binscatter stable old code, and am not ready to touch the code without refactoring it and adding tests.
