### ISSUE TITLE
Date formatted x-axis

### ISSUE THREAD

**Issue by superpronker** [michaelstepner/binscatter#20]
When the x-variable is formatted as a date, it works fine with "tlabel", "tline", etc., except when adding ticks to the tlabel. For example, 

`set obs 1000`
`g date = mdy(1,1,2000)+_n`
`g y = sin(date)`
`twoway mband y date , tlabel(01jan2000 01jan2002,format(%dmY)) // works fine`
`binscatter y date , tlabel(#10,format(%dmY)) // works fine`
`binscatter y date , tlabel(01jan2000 01jan2002,format(%dmY)) // fails`

The binscatter command will return 
`invalid ticklist "01jan1999" must be number`
`r(198);`

**Comment by michaelstepner** [comment]
I wasn't able to replicate this on my computer: I got an error with `twoway mband`. I'm running Stata 13.1 on OS X, could you specify which OS and version you're using?

```
. clear all

. set obs 1000
obs was 0, now 1000

. g date = mdy(1,1,2000)+_n

. g y = sin(date)

. twoway mband y date , tlabel(01jan2000 01jan2002,format(%dmY)) // works fine
invalid ticklist "01jan2000" must be number
r(198);
```

**Comment by superpronker** [comment]
That’s strange. I’m running Stata 14, so maybe it is a new feature that has been introduced in 14 that wasn’t there in 13? 

I am also running OS X (El Capitan). 

By the way, absolutely wonderful work you have done with the binscatter program. Brilliant! 

Anders

**Comment by michaelstepner** [comment]
Thanks Anders!

> I’m running Stata 14, so maybe it is a new feature that has been introduced in 14 that wasn’t there in 13?

That's what it seems like. Out of interest, what happens if you run:

```
version 12.1
set obs 1000
g date = mdy(1,1,2000)+_n
g y = sin(date)
twoway mband y date , tlabel(01jan2000 01jan2002,format(%dmY)) // works fine
binscatter y date , tlabel(#10,format(%dmY)) // works fine
binscatter y date , tlabel(01jan2000 01jan2002,format(%dmY)) // fails
```

**binscatter** has a `version 12.1` statement at the top of the program, which could be why it doesn't support the `tlabel()` syntax even though you're running Stata 14.

**Comment by superpronker** [comment]
Then I get: 

. twoway mband y date , tlabel(01jan2000 01jan2002,format(%dmY)) // works fine
invalid ticklist "01jan2000" must be number
r(198);

I think you hunch is absolutely right! 

Very cool, Michael!

**Comment by michaelstepner** [comment]
Glad we got to the bottom of it!

**Comment by zoniusalexandr** [comment]
FYI, I get the same results as Michael on Stata 14, OSX El Capitan. The
following lines of code work fine though:
twoway mband y date , tlabel(`=td(01jan2000)' `=td(01jan2002)',format(%dmY))
binscatter y date , tlabel(`=td(01jan2000)' `=td(01jan2002)',format(%dmY))
