### ISSUE TITLE
binscatter for interaction terms?

### ISSUE THREAD

**Issue by randomgambit** [michaelstepner/binscatter#21]
Hi Michael,

Congrats for this great piece of code. I guess `binscatter` is most useful to check the specification form, right? That is pretty important in any case.

Quick question: can we use `binscatter` to check the significance of interaction effects? What would be the correct syntax then? Does `binscatter` understands the syntax `controls(i.michael##i.michael)` ?

Thanks!

**Comment by michaelstepner** [comment]
Hi Olaf,

`binscatter` is a useful tool for visualizing the relationship with a single regressor in isolation, perhaps after controlling for other variables using `controls()` or `absorb()`.  For example:

```
sysuse auto
gen mpg_headroom = mpg*headroom
reg price mpg headroom mpg_headroom
binscatter price mpg_headroom, controls(mpg headroom) reportreg
```

But depending on what you're trying to express, this might not be the most informative plot. For example, [Bramber Clark Golder 2006](http://pan.oxfordjournals.org/content/14/1/63.full.pdf+html) discusses how to produce figures illustrating marginal effects of interaction terms.

**Comment by randomgambit** [comment]
thanks thats interesting
